export const GET_ALL_STOCKS = "GET_ALL_STOCKS";
export const GET_WATCH_LIST_STOCK = "GET_WATCH_LIST_STOCK";
export const ADD_STOCK_TO_WATCH_LIST = "ADD_STOCK_TO_WATCH_LIST";
export const DELETE_STOCK_FROM_WATCH_LIST = "DELETE_STOCK_FROM_WATCH_LIST";
export const GET_STOCK_DETAIL = "GET_STOCK_DETAIL";
export const GET_STOCK_GRAPH = "GET_STOCK_GRAPH";

//Loader
export const LOADING_START = "LOADING_START";
export const LOADING_STOP = "LOADING_STOP";

//News
export const GET_STOCK_NEWS = "GET_STOCK_NEWS";